### ISSUE TITLE
PHP usage outside of Laravel Framework does not function

### ISSUE THREAD

**Issue by Jamesking56** [doerffler/flysystem-onedrive#8]
When using the OneDrive Flysystem Adapter outside of Laravel (following the Readme), the library requires use of Laravel Facades which are not present due to being outside of Laravel:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\Support\Facades\Http::put() in /home/jamesking56/PhpstormProjects/**SNIP**/vendor/justus/flysystem-onedrive/src/OneDriveAdapter.php:206
Stack trace:
#0 /home/jamesking56/PhpstormProjects/**SNIP**/vendor/justus/flysystem-onedrive/src/OneDriveAdapter.php(189): Justus\FlysystemOneDrive\OneDriveAdapter->writeChunk()
#1 /home/jamesking56/PhpstormProjects/**SNIP**/vendor/league/flysystem/src/Filesystem.php(69): Justus\FlysystemOneDrive\OneDriveAdapter->writeStream()
#2 /home/jamesking56/PhpstormProjects/**SNIP**/backup(77): League\Flysystem\Filesystem->writeStream()
#3 {main}
  thrown in /home/jamesking56/PhpstormProjects/**SNIP**/vendor/justus/flysystem-onedrive/src/OneDriveAdapter.php on line 206
```

**Comment by Chris53897** [comment]
@Jamesking56 Can you confirm that the PR did fix the error?
In this case, could you please close this issue?
